@localhost=localhost:4004/odata/v4/main
@id=123e4567-e89b-12d3-a456-426614174000

get http://{{localhost}}/Customers
Content-Type: application/json

###
post http://{{localhost}}/Customers
Content-Type: application/json

{
    "firstName": "Marcelo",
    "lastName": "Godoy",
    "email": "marcelo@sap.com"
}


###
PUT http://{{localhost}}/Customers/{{id}}
Content-Type: application/json

{
    "firstName": "Bento",
    "lastName": "Borba",
    "email": "bento@sap.com"
}

###
DELETE http://{{localhost}}/Customers({{id}})


###
# Expandindo os itens, produtos e customers
get http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer

###

# # Expandindo os itens, produtos, customers e filtrando 
get http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 2),customer&$filter=customer/firstName eq 'Bento'



###
# Selecionar somente customers e id do sales orders header
get http://{{localhost}}/SalesOrderHeaders?$select=customer&$expand=customer($select=id,firstName,lastName)

###

get http://{{localhost}}/SalesOrderHeaders?$expand=customer($select=id,firstName,lastName,email)

###

# Descobrindo a quantidade de registros
get http://{{localhost}}/SalesOrderHeaders/$count

###

# Paginando os resultados / Registros 1 a 5
get http://{{localhost}}/SalesOrderHeaders?$top=2&$skip=0

###

#buscando dados com $search  (USAR COM CUIDADO, POIS DEPENDE DE COMO O 
#                            PROVEDOR DE SERVIÇO IMPLEMENTA O RECURSO DE PESQUISA)
get http://{{localhost}}/SalesOrderHeaders?$search=9zk1@

###
# buscando dados com $search  (USAR COM CUIDADO, POIS DEPENDE DE COMO O

get http://{{localhost}}/SalesOrderHeaders?$search=fistName

###
# Ordenando dados com $orderby  (desc = decrescente, asc = crescente)
get http://{{localhost}}/SalesOrderHeaders?$orderby=customer/firstName desc
Content-Type: application/json












# entity Customers {
#     key id        : UUID; // Chave primária do cliente
#         firstName : String(20); // Nome do cliente
#         lastName  : String(50); // Sobrenome do cliente
#         email     : String(100); // Email do cliente
# }