@localhost=localhost:4004/odata/v4/main
@id=5403024c-c21f-4a8f-8ab8-98f930afecc2
@customerId=5403024c-c21f-4a8f-8ab8-98f930afecc2
@productId=5403024c-c21f-4a8f-8ab8-98f930afecc2
@itemId1=23980619-1111-1111-1111-111111111111
@itemId2=23980620-2222-2222-2222-222222222222

@productId1=26924639-cb46-4dd3-bf1a-8b20326c2f1d  # Produto 1 sem estoque
@productId2=5403024c-c21f-4a8f-8ab8-98f930afecc2 # Produto 2 com estoque suficiente


get http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: basic godoy2:godoy2

###

post http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: basic godoy2:godoy2

{
    "id": "{{id}}",
   "customer_id": "{{customerId}}",
   "totalAmount": 200,
    "items": [
        {
            "id": "{{itemId1}}",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 2000,
            "price": 10000
        },
        {
            "id": "{{itemId2}}",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity":2000,
            "price": 50000
        }
    ]
}
###
DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: basic godoy2:godoy2

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
{
    "modifiedBy": "test"
}

###

# Buscar todos os pedidos maiores ou iguais a x
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 500000
Authorization: basic godoy2:godoy2